# env used here need to pass  via `docker compose --env-file=`
services:
  # -------------- postgres --------------
  postgres-db:
    container_name: postgres-db
    image: postgres
    # restart: always

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      # POSTGRES_DB: postgres
