/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Menu {
  available: Generated<boolean | null>;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  description: Generated<string | null>;
  id: string;
  name: string;
  price: Numeric;
  updated_at: Generated<Timestamp | null>;
}

export interface Order {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
  paid: Generated<Numeric | null>;
  seat_id: string | null;
  staff_id: string;
  total: Generated<Numeric | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface OrderItem {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  id: string;
  menu_id: string;
  menu_price: Numeric;
  order_id: string;
  quantity: number;
  status: string;
  updated_at: Generated<Timestamp | null>;
}

export interface Seat {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
  updated_at: Generated<Timestamp | null>;
}

export interface Staff {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
  updated_at: Generated<Timestamp | null>;
}

export interface DB {
  menu: Menu;
  order: Order;
  order_item: OrderItem;
  seat: Seat;
  staff: Staff;
}
